d={'name':"Neeraj","age":37,"qualification":"M.tech"}
# print(d)
# print(type(d))
# print(id(d))
# print(len(d))
# print(max(d))
# print(min(d))
# print(sum(d))
# d={1:1,2:2,3:3}
# print(d)
# print(sum(d))
# d={1:'Neeraj',2:37,'qualification':2009}
# print(d)
d={'name':'Neeraj','age':37,'qualification':'M.tech'}
# d1=d.copy()
# print(d)
# print(d1)
# # print(id(d),id(d1))
# d.clear()
# print(d)
# n=d.get('name')
# print(n)
# n=d.get('name','guest')
# print(n)
# print(d)
# n=d.get('name')
# print(n)
# n=d.get('name','guest')
# print(n)
# print(d.items())
# print(d.keys())
# print(d.values())
# x=d.pop('name')
# print(x)
# print(d)
# x=d.popitem()
# print(x)
# print(d)
# d1={'x':10,'y':20,'z':30}
# d.update(d1)
# print(d)
# print(d1)
s='python'
# d=dict.fromkeys(s)
# print(d)
# d=dict.fromkeys(s,100)
# print(d)
d.setdefault('name','Neeraj')
print(d)
# d.setdefault('p',10)
# print(d)