create database mircale;
show databases;
use mircale;
create table student( rollno int(5), name varchar(10), class varchar(10));
show tables;
insert into student( rollno ,name, class) values(111 ,'sakshi','bca');
select * from student;
insert into student( rollno ,name, class) values(112 ,'shradha','mca');
insert into student( rollno ,name, class) values(113 ,'shrishti','mba');
insert into student( rollno ,name, class) values(114 ,'nida','m.tech');
show tables;
show databases;
drop database bhopal;
create database bhopal;
show databases;
create table EMPLOYEE (Name varchar(10),Department varchar(10),City varchar(10),Salary int(7));
insert into EMPLOYEE (Name,Department,City,Salary) values('Rajesh','Admin','Bhopal',100000);
insert into EMPLOYEE (Name,Department,City,Salary) values('Solhan','Sales','Indore',5000);
insert into EMPLOYEE (Name,Department,City,Salary) values('Mohan','HR','Jablpur',5000);
insert into EMPLOYEE (Name,Department,City,Salary) values('Denesh','Finance','Gwalior',5000);
select * from EMPLOYEE;
drop database miracle;
create database miracle;
use miracle;
create table student( rollno int(10), name varchar(10), city varchar(10), class varchar(10));
insert into student(rollno, name, city, class) values (111,'shrishti','guna','bca');
insert into student( rollno, name, city, class) values(112,'shradha','mandideep','inter');
insert into student( rollno, name, city, class) values(113,'nida','nagpur','bca');
insert into student( rollno, name, city, class) values(114,'parth','kasi','btech');
insert into student( rollno, name, city, class) values(115,'kapil','itarsi','btech');
show tables;
select * from student;
select rollno,name from student;
select* from student where rollno=113;
select * from student where class='btech';
select name,rollno,city,class from student where class='bca';
select name, class from student;
select name,class from student where rollno=115;
select rollno,name,class from student where class='btech';
select name,city from student where rollno=111;
select name from student where city='guna';
select * from student where class='bca';
drop table Emp;
create table Emp ( Empno varchar(10),name varchar (10),	dept varchar(10) ,Salary int(10));
insert into Emp( Empno,name, dept,salary) values (1001,'sumit','Hr',25000);
insert into Emp( Empno,name, dept,salary) values (1002,'Sanjay','Admin',45000);
insert into Emp( Empno,name, dept,salary) values (1003,'Seema','Hr',10000);
insert into Emp( Empno,name, dept,salary) values (1004,'Anu','Sales',70000);
insert into Emp( Empno,name, dept,salary) values (1005,'Mohan','Account',40000);
insert into Emp( Empno,name, dept,salary) values (1006,'Sunita','Admin',30000);
select * from Emp;
drop table Emp;
create table Emp ( Empno varchar(10),name varchar (10),	dept varchar(10) ,Salary int(10));
insert into Emp( Empno,name, dept,salary) values (1001,'sumit','Hr',25000);
insert into Emp( Empno,name, dept,salary) values (1002,'Sanjay','Admin',45000);
insert into Emp( Empno,name, dept,salary) values (1003,'Seema','Hr',10000);
insert into Emp( Empno,name, dept,salary) values (1004,'Anu','Sales',70000);
insert into Emp( Empno,name, dept,salary) values (1005,'Mohan','Account',40000);
insert into Emp( Empno,name, dept,salary) values (1006,'Sunita','Admin',30000);
select * from Emp;
select name ,dept from Emp where Empno=1003;
select * from Emp where dept='admin';
select salary from Emp where name='Seema';
select name ,dept, salary from Emp where dept='Hr';
select Empno, name,dept from Emp where salary=70000;
select Empno, name ,dept from Emp where salary<70000;
select Empno, name ,dept from Emp where salary=highest;




show databases;
select * from student;
create database mircaleIT;
use mircaleIT;
create table emp (empno int ,name varchar(10),dept varchar(10),city varchar(10),salary int);
insert into emp( empno,name,dept,city,salary)
			values( 101,'raju','hr','bhopal',25000),
				   (102,'sanjay','admin','indore',20000),
                    (103,'dinesh','sales','satna',30000),
                     (104,'suresh','admin','mandideep',40000),
                      (105,'ramesh','marketing','indore',50000),
                       (106,'mahesh','bank','sehore',60000),
                        (107,'naresh','school','indore',70000),
                         (108,'sachin','college','jhasi',40000);
 select * from emp;
 select * from emp where salary >50000;
  select * from emp where salary >=30000;
   select * from emp where salary <40000;
    select * from emp where salary <=40000;
    select * from emp where salary between 40000 and 60000;
    select * from emp where dept="college" and city="jhasi";
    select * from emp where dept="college" or city="satna";
    select * from emp;
    select * from emp where salary <40000;
    select * from emp where salary >= 50000;
    select * from emp where salary between 20000 and 60000;
    select * from emp where city="indore" and dept="admin";
    select * from emp where dept="account" or salary> 50000;
   select * from emp where city='indore' and dept='admin';
select * from emp;
select city from emp;
select distinct city from emp;
select * from emp where city in ("bhopal","indore");
select * from emp where city not in ("bhopal","indore");
select * from emp order by name;
select * from emp order by name asc;
update emp set dept="account" where empno=102;

select *from emp;
use mircaleIT;
SET SQL_SAFE_UPDATES =0;
select * from emp order by salary desc;

select * from emp order by  dept;
select * from emp order by  name;
select * from emp order by dept;
select name ,dept from emp order by salary asc;
select dept from emp;
select * from emp;
update emp set salary=30000 where name='suresh';
select * from emp;
update emp set dept ="DJ" where city ='satna';
update emp set dept="HR",city='Ujjain' where empno=106;

select name,dept from emp order by salary asc;

select name,dept from emp order by dept asc;
select distinct salary from emp;
delete from emp where empno=108;
select * from emp;
select * from emp where name like 'r%';
select * from emp where name like 'm%';
select * from emp where name like 'n%';
select * from emp where name like 's%';
select * from emp where name like '_a%';
select * from emp where name like '%e__';
select* from emp;
delete from emp where name='naresh';
SET SQL_SAFE_UPDATES=0;
select * from emp;
delete from emp where city='jablpur' and salary>20000;
select * from emp;
use mircaleIT;
show tables;
create table student(rollno int, name varchar(10) not null,class varchar(10))  ;
show tables;
insert into student( rollno, name, class) values (111,'amit','bca');
select * from student;
insert into student( rollno, name,class) values(112,'','mca');
select * from student;
insert into student( rollno,name,class) values(null,'',null);
insert into student(rollno,name,class) values(null,'anu','mba');
select * from student;
insert into student( rollno, name, class) values(null ,'raj','mca');
insert into student( rollno, name, class) values (null,null,null);
drop table  student;
create table student(rollno int(10) unique, name varchar(10), class varchar(10));
insert into student (rollno,name,class) values(111,'amit','bca');
select * from student;
insert into student( rollno,name,class) values(111,'sumit','mcom');
insert into student( rollno,name,class) values(112,'raj','mcom');
insert into student( rollno,name,class) values(113,'raj','mcom');
 
insert into student( rollno,name,class) values(null,null,null);

show databases;
create database miracleIT;
show databases;
use miracleIT;
create table student(rollno int ,name varchar(10) not null,class varchar(10));
show tables;
insert into student (rollno,name,class)
values(111,'amit','bca');
select * from student;
insert into student(rollno,name,class)values(112,'','mca');
select * from student;
insert into student(rollno,name,class) values(null,'anu','mba');
insert into student (rollno,name,class) values(null,'raj','mca');
insert into student (rollno,name,class) values(null,null,null);
drop table student;
create table student(rollno int(10) unique,name varchar(10),class varchar(10));
insert into student (rollno,name,class) values(111,'amit','bca');
select * from student;
insert into student(rollno,name,class)values(111,'sumit','mcom');
insert into student (rollno,name,class) values(112,'raj','mcom');
insert into student (rollno,name,class) values(113,'raj','mcom');
insert into student (rollno,name ,class) values (null,null,null);
use miracleIT;
drop  table student;
create table student(rollno int(10) primary key,name varchar(10),class varchar(10)); 
insert into student( rollno,name,class)values(111,'aman','bca');
insert into student( rollno,name,class)values(111,'aman','bca');
insert into student( rollno,name,class)values(112,'aman','bca');
select * from student;
insert into student( rollno,name,class)values(null,'raju','mca');
drop table student;
drop table emp;
use mircaleIT;
drop table emp;
create table emp(
                 empno varchar(10) check (empno like 'e%'),
                 name varchar(10),
                 city varchar(10) check (city in ('bhopal','indore','jablpur')),
                 salary int(10) check(salary between 25000 and 60000)
                 );
                 
insert into emp(empno,name ,city,salary) values('e001','ramesh','bhopal',50000);    
insert into emp(empno,name ,city,salary) values('p001','ramesh','bhopal',50000);   
insert into emp(empno,name ,city,salary) values('e002','ramesh','surat',50000);
insert into emp(empno,name ,city,salary) values('e003','ramesh','bhopal',70000);
select * from emp;
insert into emp(empno,name ,city,salary) values('e002','ramesh','bhopal',40000);
insert into emp(empno,name ,city,salary) values('e003','Suresh','jablpur',40000);
drop table emp;
create table emp( rollno int(10),name varchar(10),class varchar(10) default 'btech'); 
        insert into emp (rollno,name) values (111,'rajesh');
            insert into emp (rollno,name) values (112,'ramesh');
                insert into emp (rollno,name) values (113,'suresh');
                select * from emp;
                insert into emp(rollno,name ,class) values(114,'neeraj','mtech');
                drop table stu1;
                 drop table stu2;
create table stu1(rollno int primary key,name varchar(10),class varchar(10));
create table stu2(
                  sid int, marks int,grade varchar(10),
                  foreign key(sid) references stu1(rollno)
                  );
insert into stu1 values(111,'amit','bca');
insert into stu1 values(112,'anuj','mca');
insert into stu1 values(113,'sanju','mtech');
insert into stu1 values(114,'raman','mca');
select * from stu1;
insert into stu2 values(111,560,'A');
insert into stu2 values(112,960,'A');
insert into stu2 values(113,560,'B');
insert into stu2 values(114,460,'A');
select *from stu1;
select * from stu2;
delete from stu1 where rollno=114;
select * from stu2;
delete from stu2 where sid=114;
show tables;
select * from emp;
select * from emp where rollno=114;
create index myidx on emp(rollno);
create index myidx1 on emp(rollno,name);
drop index myidx on emp;
drop index myidx1 on emp;
use miracleIT;
show tables; 
drop table student;
create table student (rollno int ,name varchar(10),class varchar(10));
show tables;
select * from student;
desc student;
alter table student add column city varchar(10);
desc student;
alter table student drop column city;
desc student;
show tables;
desc student;
alter table student rename column class to subject;
desc student;
alter table student modify column name varchar(15);
desc student;
alter table student modify column name varchar(4);
desc student;
alter table student modify column name varchar(10);
desc student;
insert into student values(111,'mayank','bca');
insert into student values(112,'raj roy','mca');
select * from student;
alter table student modify column name varchar(6);
alter table student modify column name varchar(7);
desc student;
use miracleIT;
drop table emp1;
create table emp1(empno int not null ,name varchar(10),city varchar(10),salary int(10));
insert into emp1(empno,name,city,salary)values(111,'ramesh','jablpur',35000);
insert into emp1(empno,name,city,salary)values(null,'suresh','surat',40000);
desc table emp1;
select * from emp1;
create table emp2(empno int unique ,name varchar(10),city varchar(10),salary int(10));
insert into emp2(empno,name,city,salary)values(111,'ramesh','jablpur',35000);
insert into emp2(empno,name,city,salary)values(111,'ramesh','jablpur',35000);
select * from emp2;
create table emp3(empno int primary key ,name varchar(10),city varchar(10),salary int(10));
insert into emp3(empno,name,city,salary)values(111,'ramesh','jablpur',35000);
insert into emp3(empno,name,city,salary)values(111,'suresh','jablpur',40000);
insert into emp3(empno,name,city,salary)values(null,'suresh','jablpur',40000);
drop table emp4;
create table emp4(empno varchar(10) check (empno like'e%'),name varchar(10),city varchar(10)check(city in('bhopal','indore','jablpur')),salary int(10)check (salary between 25000 and 60000));
insert into emp4(empno,name,city,salary)values(null,'suresh','jablpur',40000);
insert into emp4(empno,name,city,salary)values('r001','suresh','jablpur',40000);
insert into emp4(empno,name,city,salary)values('','suresh','jablpur',40000);
create table emp5(empno int ,name varchar(10),city varchar(10),salary int(10)default 25000);
insert into emp5(empno,name,city)values(1001,'suresh','jablpur');
select * from emp4;
select * from emp5;
insert into emp5(empno,name,city,salary)values(1001,'suresh','jablpur',70000);
select * from emp5;
drop table student;
create table student(rollno int,name varchar(10),class varchar(10));
alter table student add column city varchar(10);
select * from student;
desc student;

alter table student drop column city;
alter table student modify column subject int(120);
show tables;
alter table student rename column class to subject;
alter table student modify column subject int not null;
alter table student modify column subject int ;
alter table student modify column subject varchar(20) ;
alter table student add unique (rollno);
alter table student add unique (name);
alter table student drop index rollno;
alter table student drop index name;
alter table student add primary key (rollno);
alter table student drop primary key;
alter table student modify column rollno int;
use miracleIT;
show tables;
desc student;
alter table student add primary key(rollno);
create table sturesult (sid int ,marks int,grade varchar(10));
desc sturesult;
alter table sturesult add foreign key(sid) references student(rollno);
show create table sturesult;
alter table sturesult drop foreign key sturesult_ibfk_1;
alter table student add check (rollno>=100);
show create table student;
alter table student drop check student_chk_1;
desc student;
alter table student alter subject set default 10000;
alter table student alter subject drop default;
select * from student;
select * from product;
use miracleit;
create table product(pno int,name varchar(10),qty int,rate int,total int);
insert into product(pno,name,qty,rate) values(1002,'cpu',2,2400);
insert into product(pno,name,qty,rate) values(1001,'mouse',2,250);
insert into product(pno,name,qty,rate) values(1002,'key board',2,2400);
insert into product(pno,name,qty,rate) values(1001,'mouse',2,250);
insert into product(pno,name,qty,rate) values(1003,'monitor',2,250);
insert into product(pno,name,qty,rate) values(1001,'mouse',5,2580);
insert into product(pno,name,qty,rate) values(1004,'joy stick',2,250);
insert into product(pno,name,qty,rate) values(1001,'mouse',2,250);
select * from product;
set sql_safe_updates=0;
update product set total=qty*rate;
select sum(total) as "Total Amount" from product;
select sum(total) "Grand Total " from product;
select name,sum(total) as "Total Amount" from product group by name;
select name,avg(total) as "total amount" from product  group by name;
select name,max(total) as "total amount" from product  group by name;
select name,count(total) as "total amount" from product group by name;
select name,sum(qty),sum(total) from product group by name;
select pno,name,sum(qty),sum(total) from product group by name,pno;
select qty, pno,name,sum(qty),sum(total) from product group by name,pno,qty;